spring:
  application:
    name: auth-service  # Identifier of this application

server.port: 4444

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # URL of the eureka server for registration